<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.validator.front_controller' shared service.

return $this->services['ps_checkout.validator.front_controller'] = new \PrestaShop\Module\PrestashopCheckout\Validator\FrontControllerValidator(${($_ = isset($this->services['ps_checkout.validator.merchant']) ? $this->services['ps_checkout.validator.merchant'] : $this->load('getPsCheckout_Validator_MerchantService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.express_checkout.configuration']) ? $this->services['ps_checkout.express_checkout.configuration'] : $this->load('getPsCheckout_ExpressCheckout_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.pay_in_4x.configuration']) ? $this->services['ps_checkout.pay_in_4x.configuration'] : $this->load('getPsCheckout_PayIn4x_ConfigurationService.php')) && false ?: '_'});
