version: "3.9"
services:
  apache:
    build:
      context: ./apache
      args:
        DOCKER_USER_ID: $DOCKER_USER_ID  
    ports:       
      - 8080:80
    volumes:
        - ${PWD}/html:/var/www/html
  db:
    image: mariadb:latest  
    user: $DOCKER_USER_ID:$DOCKER_GROUP_ID
    env_file:
      - .env
    volumes:
      - ${PWD}/db:/var/lib/mysql
    ports:       
      - 127.0.0.1:3306:3306

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
