version: "3.9"
services:
    apache:
        image: httpd
        ports:
            - 8080:80
        volumes:
            - ./html:/usr/local/apache2/htdocs
    bd:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: example
        
    phpmyadmin:
        image: phpmyadmin

