<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3h42kdg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3h42kdg/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3h42kdg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3h42kdg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3h42kdg\appProdProjectContainer([
    'container.build_hash' => '3h42kdg',
    'container.build_id' => '28026d8c',
    'container.build_time' => 1647266272,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3h42kdg');
