<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEpejdxo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEpejdxo/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEpejdxo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEpejdxo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEpejdxo\appProdProjectContainer([
    'container.build_hash' => 'Epejdxo',
    'container.build_id' => 'db3dddeb',
    'container.build_time' => 1646924019,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEpejdxo');
